version: '3.8'

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service_app
    ports:
      - "8001:8001"
    volumes:
      - ./auth_service:/app      # For live code reload
      - auth_db_data:/app/data   # For persistent database data ONLY
    env_file:
      - ./auth_service/.env

  transcription_service:
    build: ./audio_transcription
    container_name: transcription_service_app
    ports:
      - "8000:8000"
    volumes:
      - ./audio_transcription:/app
    env_file:
      - ./audio_transcription/.env
    depends_on:
      - auth_service

volumes:
  auth_db_data: