version: '3.8'

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service_app
    volumes:
      - auth_db_data:/app/data
    env_file:
      - ./auth_service/.env

  transcription_service:
    build: ./audio_transcription
    container_name: transcription_service_app
    env_file:
      - ./audio_transcription/.env
    depends_on:
      - auth_service

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - transcription_service

volumes:
  auth_db_data: