services:
  auth_api:
    build: .
    container_name: auth_api_app
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app